//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicSum.Main.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState BrowserWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["BrowserWindowState"]));
            }
            set {
                this["BrowserWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point BrowserLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowserLocation"]));
            }
            set {
                this["BrowserLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size BrowserSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowserSize"]));
            }
            set {
                this["BrowserSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int FileListPageThumbnailSize {
            get {
                return ((int)(this["FileListPageThumbnailSize"]));
            }
            set {
                this["FileListPageThumbnailSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileListPageIsShowFileName {
            get {
                return ((bool)(this["FileListPageIsShowFileName"]));
            }
            set {
                this["FileListPageIsShowFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileListPageIsShowImageFile {
            get {
                return ((bool)(this["FileListPageIsShowImageFile"]));
            }
            set {
                this["FileListPageIsShowImageFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileListPageIsShowDirectory {
            get {
                return ((bool)(this["FileListPageIsShowDirectory"]));
            }
            set {
                this["FileListPageIsShowDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Single")]
        public global::PicSum.Core.Base.Conf.ImageDisplayMode ImageViewerPageImageDisplayMode {
            get {
                return ((global::PicSum.Core.Base.Conf.ImageDisplayMode)(this["ImageViewerPageImageDisplayMode"]));
            }
            set {
                this["ImageViewerPageImageDisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FitAllImage")]
        public global::PicSum.Core.Base.Conf.ImageSizeMode ImageViewerPageImageSizeMode {
            get {
                return ((global::PicSum.Core.Base.Conf.ImageSizeMode)(this["ImageViewerPageImageSizeMode"]));
            }
            set {
                this["ImageViewerPageImageSizeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileListPageIsShowOthereFile {
            get {
                return ((bool)(this["FileListPageIsShowOthereFile"]));
            }
            set {
                this["FileListPageIsShowOthereFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportDirectoryPath {
            get {
                return ((string)(this["ExportDirectoryPath"]));
            }
            set {
                this["ExportDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int FileListPageFavoriteDirectoryCount {
            get {
                return ((int)(this["FileListPageFavoriteDirectoryCount"]));
            }
            set {
                this["FileListPageFavoriteDirectoryCount"] = value;
            }
        }
    }
}
