name: release

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: setup-nuget
        uses: nuget/setup-nuget@v2

      - name: dotnet restore 
        run: dotnet restore src\PicSum.sln

      - name: msbuild
        run: >
          msbuild
          src\PicSum.sln
          /t:Rebuild
          /p:Configuration=Release
          /p:Platform="Any CPU"
          /p:OutputPath=$pwd\dist\picsum
          /p:GenerateDependencyFile=false
      
      - name: cleanup
        shell: pwsh
        run: |
          Remove-Item -Path "$pwd\dist\picsum\NLog.debug.config" -Force
          Remove-Item -Path "$pwd\dist\picsum\*.pdb" -Force
          Rename-Item -Path "$pwd\dist\picsum\picsum.runtimeconfig.json" -NewName "temp"
          Remove-Item -Path "$pwd\dist\picsum\*.runtimeconfig.json" -Force
          Rename-Item -Path "$pwd\dist\picsum\temp" -NewName "picsum.runtimeconfig.json"
          Copy-Item -Path "$pwd\doc\MANUAL.md" -Destination "$pwd\dist\MANUAL.txt"
          Copy-Item -Path "$pwd\doc\CHANGELOG.md" -Destination "$pwd\dist\CHANGELOG.txt"

      - name: compress archive 
        shell: pwsh
        run: |
          compress-archive dist\* picsum.zip

      - name: action-gh-release 
        uses: softprops/action-gh-release@v2 
        with:
          files: |
            picsum.zip
