name: release

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          dotnet-version: '8.0'         
          msbuild-architecture: 'x64'

      - name: setup-nuget
        uses: nuget/setup-nuget@v2

      - name: dotnet restore 
        run: dotnet restore src\PicSum.sln

      - name: msbuild
        run: >
          msbuild
          src\PicSum.sln
          /t:Publish
          /p:Configuration=Release
          /p:OutputPath=$pwd\dist\picsum
          /p:Platform="x64"
          /p:RuntimeIdentifier="win-x64"
      
      - name: set docs
        shell: pwsh
        run: |
          Remove-Item "$pwd\dist\picsum\*.dll" -Force 
          Remove-Item "$pwd\dist\picsum\*.json" -Force 
          Remove-Item "$pwd\dist\picsum\runtimes" -Recurse -Force
          Copy-Item -Path "$pwd\doc\MANUAL.md" -Destination "$pwd\dist\MANUAL.txt"
          Copy-Item -Path "$pwd\doc\CHANGELOG.md" -Destination "$pwd\dist\CHANGELOG.txt"
          Copy-Item -Path "$pwd\LICENSE" -Destination "$pwd\dist\LICENSE.txt"
          Copy-Item -Path "$pwd\PrivacyPolicy" -Destination "$pwd\dist\PrivacyPolicy.txt"

      - name: compress archive 
        shell: pwsh
        run: |
          $tag_name = "${{ github.ref }}" -split '/' | Select-Object -Last 1
          compress-archive dist\* picsum-$tag_name.zip

      - name: action-gh-release 
        uses: softprops/action-gh-release@v2 
        with:
          files: |
            picsum-*.zip

